### ISSUE TITLE
Comparison with original MATLAB scripts from Chartrand

### ISSUE THREAD

**Issue by billtubbs** [stur86/tvregdiff#2]
Has any testing been done to compare the outputs of `TVRegDiff` with Chartrand's original MATLAB code?

I see he has a couple of demo's included in [his code](https://sites.google.com/site/dnartrahckcir/home/tvdiff-code):
- `demo_large.m`
- `demo_small.m`

I tried running `tvregdiff` with the same parameters as `demo_small.m` but couldn't get exactly the same results.  Maybe I am doing something wrong.

**Comment by billtubbs** [comment]
Here is my test script:

```
noisy_abs_data = np.loadtxt('smalldemodata.csv')  # data from smalldemodata.mat
n_iters = 500
alph = 0.2
scale = 'small'
ep = 1e-6
dx =  0.01
u = TVRegDiff(noisy_abs_data, n_iters, alph, u0=None, scale=scale, 
                      ep=ep, dx=dx, plotflag=False, diagflag=True)
```

**Comment by billtubbs** [comment]
Could be a problem with my test setup.  I'm getting the `"WARNING:root:WARNING - convergence to tolerance not achieved!"` warning on every iteration.  

I tried varying the number of iterations.  The results seem to be heading towards the values I got from running Chartrand's MATLAB script.

![tvregdiff_tests](https://user-images.githubusercontent.com/7958850/69361889-3bddfc00-0c42-11ea-9d76-dcba75d549eb.png)

So I'm thinking that maybe I need to adjust one of the parameters to make this converge.  Any advice on what to try next?

**Comment by billtubbs** [comment]
This is from using his 'noisy abs data' (from [`smalldemodata.mat`](https://sites.google.com/site/dnartrahckcir/home/tvdiff-code)) which looks like this:

![smalldemodata](https://user-images.githubusercontent.com/7958850/69362172-d9393000-0c42-11ea-94c9-fb041f76fbbb.png)

**Comment by warren55555** [comment]
I have the same issue. In fact, it will never converge, no matter how large you make the `n_iters` variable. You can make it converge by modifying the `maxit` variable in the `tvregdiff.py` file. However, this makes the routine extremely slow, and I had to increase the number of iterations to more than 5000 in order to get rid of all the `WARNING:root:WARNING - convergence to tolerance not achieved!` errors.
![Figure_0](https://user-images.githubusercontent.com/58997537/75086421-ed225580-5501-11ea-9847-dac517bc5a88.png)

**Comment by billtubbs** [comment]
Not sure what to do.  I don't have time right now but at some point it would be good to work through the demo example in both MATLAB and Python and figure out where they diverge and why maybe?

**Comment by jiweiqi** [comment]
I could get good results for small_dataset by disabling the preconditioner matrix P. You can also have a try. I suspect that the difference between Python and Matlab code is due to the difference between sparse.linalg.cg and Matlab pcg, although there are supposed to be equivalent.

**Comment by stur86** [comment]
I made some changes to address this. Two things, mainly:

* added a flag to disable the preconditioner if one wishes to (it was the cause of many of those 'convergence not achieved' error messages, and did nothing good)
* added a new mode of weighing the second derivative in the functional. In Rick's original script and paper it's |u'|, which results in a non-linear operator that is then approximated iteratively. However I see no reason why it can't be (u')^2, which in fact gives a linear operator and works better in some cases (specifically the ones where the derivative we're looking for does not have any steps). So now that's an option too, `diffkernel='sq'`. 

I've also changed the testing a bit, now the data is generated on the fly and new functions to test can be added. The tolerances achievable are pretty low though. I agree that something must be different between Scipy and Matlab, because clearly the results aren't always exactly the same.

**Comment by billtubbs** [comment]
Thanks for looking at this.

B.t.w. I haven't look at it but this recent paper from University of Washington might be worth looking at:

Numerical differentiation of noisy data: A unifying multi-objective optimization framework
Floris van Breugel, J. Nathan Kutz, Bingni W. Brunton
https://arxiv.org/abs/2009.01911

It references the Chartrand algorithm and includes a Python library (https://github.com/florisvb/PyNumDiff) but not sure if it includes an implementation.
